### ISSUE TITLE
Can't install/run it

### ISSUE THREAD

**Issue by ChacaGhost** [Abdelrhman-AK/WinPaletter#144]
So somehow I can't install/run the program, here is the error.

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Thursday, May 11, 2023 7:32:37 PM"
OS = "Microsoft Windows 11 Pro Education - 10.0.22621.1555 - 64-bit"
WinPaletter.Version = "1.0.7.6"

'Error details
'-----------------------------------------------------------
Exception.message = "Parameter is not valid."
Exception.stack.trace = {
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at WinPaletter.My.MyApplication.GetWallpaper()
   at WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "FromStream @ System.Drawing"
Exception.assembly = "System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll"
Exception.HRESULT = "-2147024809"
```

and this is the screenshot
![Screenshot 2023-05-11 193147](https://github.com/Abdelrhman-AK/WinPaletter/assets/128496529/794ed175-53df-46a8-a7d0-c5380e197b1d)

**Comment by ChacaGhost** [comment]
It worked! thank you.

**Comment by Abdelrhman-AK** [comment]
You're welcome!
