### ISSUE TITLE
Crashes on Windows 11 Insider Build 23471

### ISSUE THREAD

**Issue by jcchikikomori** [Abdelrhman-AK/WinPaletter#147]
## **Describe the bug**

Exception error on newer insider builds for Windows 11.

## **WinPaletter Log**

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Monday, June 5, 2023 2:31:44 PM"
OS = "Microsoft Windows 11 Pro Insider Preview - 10.0.23471.1000 - 64-bit"
WinPaletter.Version = "1.0.7.6"

'Error details
'-----------------------------------------------------------
Exception.message = "Object reference not set to an instance of an object."
Exception.stack.trace = {
   at WinPaletter.WinTerminal..ctor(String str, Mode Mode, Version Version)
   at WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreWTerminal)
   at WinPaletter.MainFrm.MainFrm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = ".ctor @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.7.6, Culture=neutral, PublicKeyToken=null"
Exception.assembly.file = "D:\WinPaletter.exe"
Exception.HRESULT = "-2147467261"
```

## **Screenshots**
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/4709030/b7952619-c007-460b-8759-d0db6d13067e)

## **Additional context**
I tried using this [workaround](https://github.com/Abdelrhman-AK/WinPaletter/issues/55#issuecomment-1296270295), and it still doesn't work.

**Comment by Abdelrhman-AK** [comment]
- Which version of Windows Terminal you have ? (Stable or Preview?)
- Try opening Windows Terminal itself and see if there is an error message in Windows Terminal
- If there is no error message, try to launch WinPaletter as Administrator and tell me. WinPaletter might not be able to access Windows Terminal JSON preferences file.
