### ISSUE TITLE
Getting exception errors when starting & exiting

### ISSUE THREAD

**Issue by nsde** [Abdelrhman-AK/WinPaletter#150]
My PC specs can be found at https://onlix.me/pc

![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/67185896/d4289318-21ca-42c2-bc01-f3588d4478cd)

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Friday, 9 June 2023 21:31:04"
OS = "Microsoft Windows 10 Home - 10.0.19045.3031 - 64-bit"
WinPaletter.Version = "1.0.7.6"

'Error details
'-----------------------------------------------------------
Exception.message = "Object reference not set to an instance of an object."
Exception.stack.trace = {
   at WinPaletter.MainFrm.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "OnFormClosing @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.7.6, Culture=neutral, PublicKeyToken=null"
Exception.assembly.file = "C:\Users\Lynx\Downloads\WinPaletter.exe"
Exception.HRESULT = "-2147467261"
```

**Comment by Abdelrhman-AK** [comment]
I'll fix it

- Does it give you "Object reference not set to an instance of an object." on startup too or they are different?

**Comment by nsde** [comment]
These are the error details I get when starting the program:

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Friday, 9 June 2023 21:49:29"
OS = "Microsoft Windows 10 Home - 10.0.19045.3031 - 64-bit"
WinPaletter.Version = "1.0.7.6"

'Error details
'-----------------------------------------------------------
Exception.message = "Object reference not set to an instance of an object."
Exception.stack.trace = {
   at WinPaletter.WinTerminal..ctor(String str, Mode Mode, Version Version)
   at WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreWTerminal)
   at WinPaletter.MainFrm.MainFrm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = ".ctor @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.7.6, Culture=neutral, PublicKeyToken=null"
Exception.assembly.file = "C:\Users\Lynx\Downloads\WinPaletter.exe"
Exception.HRESULT = "-2147467261"
```

**Comment by Abdelrhman-AK** [comment]
I fixed this error in version 1.0.7.7. Update to it and it will be fixed.

**Comment by nsde** [comment]
Thanks. You're a legend for respond this quick

**Comment by Abdelrhman-AK** [comment]
You're welcome!
