### ISSUE TITLE
There is a System.ArgumentExeption error

### ISSUE THREAD

**Issue by whitelightning76** [Abdelrhman-AK/WinPaletter#160]
Hello!

I get this error message when i start up the program.

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Wednesday, 21 June 2023 07:26:25"
OS = "Microsoft Windows 11 Pro Insider Preview - 10.0.23481.1000 - 64-bit"
WinPaletter.Version = "1.0.7.8"

'Error details
'-----------------------------------------------------------
Exception.message = "Value of '0' is not valid for 'emSize'. 'emSize' should be greater than 0 and less than or equal to System.Single.MaxValue.
Parameter name: emSize"
Exception.type = "System.ArgumentException"
Exception.stack.trace = {
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit)
   at WinPaletter.CP.Structures.MetricsFonts.AdjustFont(Font Font)
   at WinPaletter.CP.Structures.MetricsFonts.Load(MetricsFonts _DefMetricsFonts)
   at WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreExtractionThemePack)
   at WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "Initialize @ System.Drawing"
Exception.assembly = "System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll"
Exception.HRESULT = "-2147024809"
```

I have to mention I am running Windows 11 23481 (Insider Dev). 
I am not sure i get the error because of that, but just reporting the error just to be sure.

**Comment by Abdelrhman-AK** [comment]
I'll fix this error in next version.

**Comment by whitelightning76** [comment]
alright , thanks!   Looking forward to it!

**Comment by Abdelrhman-AK** [comment]
You're welcome!

**Comment by hongjr03** [comment]
Having the same problem on the latest version.

**Comment by Abdelrhman-AK** [comment]
I'll investigate about this.

**Comment by thenoelboi** [comment]
Guys? It's Back!
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/86941623/d4776f23-c6b3-40e6-a5e3-756e46fe01d7)

**Comment by Abdelrhman-AK** [comment]
- Can you scroll up this error to see more details?
- The fix I made will be posted soon in the next update.

**Comment by thenoelboi** [comment]
Hey! You replied!
Here's the full log:
(Love your app btw)


```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "23 August 2023 18:47:53"
OS = "Microsoft Windows 11 Home - 10.0.22631.2199 - 64-bit"
WinPaletter.Version = "1.0.7.9"

'Error details
'-----------------------------------------------------------
Exception.message = "Value of '0' is not valid for 'emSize'. 'emSize' should be greater than 0 and less than or equal to System.Single.MaxValue.
Parameter name: emSize"
Exception.type = "System.ArgumentException"
Exception.stack.trace = {
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit)
   at WinPaletter.CP.Structures.MetricsFonts.AdjustFont(Font Font)
   at WinPaletter.CP.Structures.MetricsFonts.Load(MetricsFonts _DefMetricsFonts)
   at WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreExtractionThemePack)
   at WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "Initialize @ System.Drawing"
Exception.assembly = "System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll"
Exception.HRESULT = "-2147024809"
```

**Comment by Abdelrhman-AK** [comment]
This bug will be fixed in the next update.

> (Love your app btw)

Thank you. I appreciate that!
