### ISSUE TITLE
"System.NullReferenceException" when applying themes

### ISSUE THREAD

**Issue by AuRiMaS666** [Abdelrhman-AK/WinPaletter#163]
## **Describe the bug**

Every single time I apply a theme, this error jumps out at the beginning of the process. I hit Continue and everything applies and seems to work correctly in the end.

## **WinPaletter Log**

````vbnet
'General information
'-----------------------------------------------------------
Report.Date = "2023 m. liepos 6 d., ketvirtadienis 11:11:05"
OS = "Microsoft Windows 11 Pro - 10.0.22621.1848 - 64-bit"
WinPaletter.Version = "1.0.7.8"

'Error details
'-----------------------------------------------------------
Exception.message = "Object reference not set to an instance of an object."
Exception.type = "System.NullReferenceException"
Exception.stack.trace = {
   at WinPaletter.CP.Structures.WinEffects.Apply()
   at WinPaletter.CP._Lambda$__68-16()
   at WinPaletter.CP.Execute(MethodInvoker Sub, TreeView TreeView, String StartStr, String ErrorStr, String TimeStr, Stopwatch overallStopwatch, Boolean Skip, String SkipStr, Boolean ExecuteEvenIfSkip)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "Apply @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.7.8, Culture=neutral, PublicKeyToken=null"
Exception.assembly.file = "E:\Software\WinPaletter.exe"
Exception.HRESULT = "-2147467261"
````

## **Screenshots/Screen records**

![2023-07-06 11 15 28](https://github.com/Abdelrhman-AK/WinPaletter/assets/59185222/095b3f15-3913-4745-90ee-6891d688374b)

**Comment by Abdelrhman-AK** [comment]
I'll fix this issue
