### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PH-ANT-OM** [Abdelrhman-AK/WinPaletter#165]
Report.Date = "Tuesday, July 18, 2023 16:52:30"
OS = "Microsoft Windows 11 Pro - 10.0.22621.1992 - 64-bit"
WinPaletter.Version = "1.0.7.6"

'Error details
'-----------------------------------------------------------
Exception.message = "Object reference not set to an instance of an object."
Exception.stack.trace = {
   at WinPaletter.Metrics_Fonts.SetToClassicWindow(RetroWindow Window, CP CP, Boolean Active)
   at WinPaletter.Metrics_Fonts.EditFonts_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "SetToClassicWindow @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.7.6, Culture=neutral, PublicKeyToken=null"
Exception.assembly.file = "D:\Others\Softwares\winpaletter-1-0-7-6.exe"
Exception.HRESULT = "-2147467261"
```
Everytime I open app it shows this error and if I click on continue then the app opens and again the popup error comes when click on any option like close or apply etc.

**Comment by Abdelrhman-AK** [comment]
Try to use the latest beta version `1.0.7.9` and tell me if this error occurs again or not.

**Comment by PH-ANT-OM** [comment]
Thank You now this version is working properly.

**Comment by Abdelrhman-AK** [comment]
The issue is fixed for you, but it is still persistent in 200% DPI.
Tell me your DPI so I will test it, and all fixes will be available in next update.

**Comment by Abdelrhman-AK** [comment]
You're welcome!

**Comment by PH-ANT-OM** [comment]
I am using 100% DPI in windows 11.

**Comment by Abdelrhman-AK** [comment]
I'm sorry I have mistaken and wrote DPI issue here. Your issue is fixed and you can ignore what I previously wrote.
