### ISSUE TITLE
System.IO.FileNotFoundException error

### ISSUE THREAD

**Issue by Locodegree** [Abdelrhman-AK/WinPaletter#167]
```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Wednesday, August 2, 2023 6:02:58 AM"
OS = "Microsoft Windows 11 Home - 10.0.22621.1992 - 64-bit"
WinPaletter.Version = "1.0.7.9"

'Error details
'-----------------------------------------------------------
Exception.message = "File not found."
Exception.type = "System.IO.FileNotFoundException"
Exception.stack.trace = {
   at Microsoft.VisualBasic.Interaction.Shell(String PathName, AppWinStyle Style, Boolean Wait, Int32 Timeout)
   at WinPaletter.MainFrm.XenonButton28_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at WinPaletter.XenonButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "Shell @ Microsoft.VisualBasic"
Exception.assembly = "Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll"
Exception.HRESULT = "-2147024894"
```

**Comment by Abdelrhman-AK** [comment]
I'll fix it
