### ISSUE TITLE
When i try to install WinPaletter Error

### ISSUE THREAD

**Issue by yasirfaheem** [Abdelrhman-AK/WinPaletter#173]
When I download and double-click the file WinPaletter.exe I get an error so I can not install the software.  I downloaded version 1.0.8.0  The error is -

```vbnet
'General information
'-----------------------------------------------------------
Report.Date = "Monday, September 4, 2023 1:49:06 PM"
OS = "Microsoft Windows 10 Enterprise - 10.0.19045.3324 - 64-bit"
WinPaletter.Version = "1.0.8.0"

'Error details
'-----------------------------------------------------------
Exception.message = "Conversion from string "" to type 'Integer' is not valid."
Exception.type = "System.InvalidCastException"
Exception.stack.trace = {
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
   at WinPaletter.CP.Structures.ScreenSaver.Load(ScreenSaver _DefScrSaver)
   at WinPaletter.CP..ctor(CP_Type CP_Type, String File, Boolean IgnoreExtractionThemePack)
   at WinPaletter.My.MyApplication.MyApplication_Startup(Object sender, StartupEventArgs e)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartup(StartupEventArgs eventArgs)
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "ToInteger @ Microsoft.VisualBasic"
Exception.assembly = "Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll"
Exception.HRESULT = "-2147467262"
Inner.exception.message = "Input string was not in a correct format."
Exception.type = "System.FormatException"
Inner.exception.stack.trace = {
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
         }
Inner.exception.data = "There is no included data in Inner exception"
Inner.exception.target.sub_function = "ParseDouble @ Microsoft.VisualBasic"
Inner.exception.assembly = "Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
Inner.exception.assembly.file = "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.VisualBasic\v4.0_10.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualBasic.dll"
Inner.exception.HRESULT = "-2146233033"
```

[WinPaletter Error.txt](https://github.com/Abdelrhman-AK/WinPaletter/files/12515750/WinPaletter.Error.txt)

**Comment by Abdelrhman-AK** [comment]
Open Registry Editor and send me a screenshot to key `HKEY_CURRENT_USER\Control Panel\Desktop` with these 3 values `ScreenSaveActive`, `ScreenSaverIsSecure`, `ScreenSaveTimeOut`

**Comment by yasirfaheem** [comment]
ScreenSaveActive REG_SZ 1
ScreenSaverIsSecure REG_SZ 1
ScreenSaveTimeOut REG_SZ No Data

**Comment by Abdelrhman-AK** [comment]
I'll fix it.
