### ISSUE TITLE
Can't save translates

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#183]
## **Describe the bug**
"Save into open file" button not work

## **WinPaletter Log**
```Exception.message = "Object reference not set to an instance of an object."
Exception.type = "System.NullReferenceException"
Exception.stack.trace = {
   at WinPaletter.Lang_JSON_GUI.data_CellEndEdit(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
   at System.Windows.Forms.DataGridView.SetCurrentCellAddressCore(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(HitTestInfo hti, Boolean isShiftDown, Boolean isControlDown)
   at System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "data_CellEndEdit @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.8.1, Culture=neutral, PublicKeyToken=null"
Exception.HRESULT = "-2147467261"
```

```
Exception.message = "Object reference not set to an instance of an object."
Exception.type = "System.NullReferenceException"
Exception.stack.trace = {
   at WinPaletter.Lang_JSON_GUI.Button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at WinPaletter.UI.WP.Button.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
         }
Exception.data = "There is no included data in Exception"
Exception.target.sub_function = "Button2_Click @ WinPaletter"
Exception.assembly = "WinPaletter, Version=1.0.8.1, Culture=neutral, PublicKeyToken=null"
Exception.HRESULT = "-2147467261"
```
## **Screenshots/Screen records**
Don't add screenshot if you already wrote WinPaletter Log.

If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
I think it's not cause of JSON file, maybe

**Comment by Abdelrhman-AK** [comment]
> I think it's not cause of JSON file, maybe
- Yup, it is due to a bug in data grid view control.
- I'll fix it and will push the update soon.
