### ISSUE TITLE
:x: [Error] can't launch 1.0.8.2

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#198]
## **Describe the error**
- can't launch WinPaletter anymore after update to 1.0.8.2

## **How to reproduce the error**
- auto update to 1.0.8.2

## **WinPaletter Log**
even couldn't be launched so there's no log

## **Screenshots/Screen records**
none

## **Additional context**
- Add any other context about the problem here.
Application: WinPaletter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at WinPaletter.Program.Domain_UnhandledException(System.Object, System.UnhandledExceptionEventArgs)

오류 있는 응용 프로그램 이름: WinPaletter.exe, 버전: 1.0.8.2, 타임스탬프로: 0xba108b36
오류 있는 모듈 이름: KERNELBASE.dll, 버전: 10.0.25997.1000, 타임스탬프: 0xb73984e0
예외 코드: 0xe0434352
오류 오프셋: 0x00150a94
오류 처리 ID: 0x22D4
오류 응용 프로그램 시작 시간: 0x1DA1E4DB16D745C

오류 버킷 1887892760028338230, 유형 5
이벤트 이름: CLR20r3
응답: 사용할 수 없음
Cab ID: 0

문제 서명:
P1: WinPaletter.exe
P2: 1.0.8.2
P3: ba108b36
P4: WinPaletter
P5: 1.0.8.2
P6: ba108b36
P7: 4af
P8: b0
P9: System.Exception
P10:

**Comment by Abdelrhman-AK** [comment]
- Can you try using WinPaletter-DEBUG.exe with WinPaletter.pdb in the same folder? More details should be visible in bug dialog.

- Try removing WinPaletter settings key in registry:
`HKEY_CURRENT_USER\Software\WinPaletter\Settings`

- WinPaletter might not have full access to `Program Files` folder. Try to create `WinPaletter` folder inside `Program Files` and try again.

**Comment by MuscularPuky** [comment]
it's trying to find Win32_UserProfile "S-1-5-82-4068219030-1673637257-3279585211-533386110-4122969689" but fail.

```cs
   {
         at WinPaletter.User.IsAdmin(String SID) in F:\\Projects\\WinPaletter\\WinPaletter\\Program\\Users\\User.cs:line 547
         at WinPaletter.UserSwitch.ListUsers(Dictionary`2 UsersList) in F:\\Projects\\WinPaletter\\WinPaletter\\Dialogs\\UserSwitch.cs:line 70
         at WinPaletter.UserSwitch.PickUser(Dictionary`2 UsersList) in F:\\Projects\\WinPaletter\\WinPaletter\\Dialogs\\UserSwitch.cs:line 116
         at WinPaletter.Program.InitializeApplication(Boolean ShowLoginDialog) in F:\\Projects\\WinPaletter\\WinPaletter\\Program\\Program.cs:line 56
         at WinPaletter.Program.Main(String[] args) in F:\\Projects\\WinPaletter\\WinPaletter\\Program\\Program.cs:line 35
   };
```

**Comment by Abdelrhman-AK** [comment]
- I'll fix it and push the update soon.
