### ISSUE TITLE
Error after Replace Font v1.0.8.4

### ISSUE THREAD

**Issue by YKefasu** [Abdelrhman-AK/WinPaletter#226]
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/129555908/e9a3ae8f-ec7c-4f36-b7c4-ab56cc834712)

```cs
//General information
//...........................................................
   Report.Date = "2024年3月21日 14:45:02";
   OS = "Windows 11, 10.0.22621.3296, 64-bit";
   WinPaletter.Version = "1.0.8.4";

//Error details
//...........................................................
   Exception.message = "Font 'Segoe UI Black' cannot be found.";
   Exception.type = "System.ArgumentException";
   Exception.stack.trace =
   {
         at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
         at System.Drawing.FontFamily..ctor(String name)
         at WinPaletter.Paths.Help(Rectangle Rectangle, ArrowStyle Style, Single Scale)
         at WinPaletter.Paths.Draw(CursorOptions CursorOptions)
         at WinPaletter.UI.Controllers.CursorControl.OnPaint(PaintEventArgs e)
         at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
         at System.Windows.Forms.Control.WmPaint(Message& m)
         at System.Windows.Forms.Control.WndProc(Message& m)
         at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
         at System.Windows.Forms.ContainerControl.WndProc(Message& m)
         at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
         at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
         at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   };
   Exception.target.void_function = "System.Drawing.CreateFontFamily()";
   Exception.assembly = "System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a";
   Exception.assembly.file = "C:\\WINDOWS\\Microsoft.Net\\assembly\\GAC_MSIL\\System.Drawing\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\System.Drawing.dll";
   Exception.HRESULT = -2147024809;
```

**Comment by Abdelrhman-AK** [comment]
Use 1.0.8.8, it is fixed there.
Another solution, you can reinstall Segoe UI Black fonts.

**Comment by YKefasu** [comment]
Thankyou
