### ISSUE TITLE
❌ WinPaletter crash after replace Segoe UI font

### ISSUE THREAD

**Issue by Andrew-Sor** [Abdelrhman-AK/WinPaletter#228]
## **Describe the error**
WinPaletter crash after replace Segoe UI font, but the system is working fine.

## **How to reproduce the error**

- Open WinPaletter
- Go to "Metrics & Font"
- Go to font replacement section
- Replace Segoe UI with any one
- Apply changes
- Log out and log in again
- Open WinPaletter again

## **WinPaletter Log**
```cs
//General information
//...........................................................
   Report.Date = "8 апреля 2024 г. 19:48:19";
   OS = "Windows 11, 10.0.22631.3374, 64-bit";
   WinPaletter.Version = "1.0.9.0, Build: Release";
   WinPaletter.Language = "Russian";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "Error creating form: Object reference not set to an instance of an object.";
   Exception.type = "System.InvalidOperationException";
   Exception.stack.trace =
   {
      at WinPaletter.Forms.CreateInstance[T](T instance)
      at WinPaletter.Forms.get_MainForm()
      at WinPaletter.User.OnUserSwitch(UserChangeEventArgs e)
      at WinPaletter.User.set_SID(String value)
      at WinPaletter.UserSwitch.Button1_Click(Object sender, EventArgs e)
      at System.Windows.Forms.Control.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnClick(EventArgs e)
      at WinPaletter.UI.WP.Button.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
      at WinPaletter.UI.WP.Button.OnMouseUp(MouseEventArgs e)
      at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.ButtonBase.WndProc(Message& m)
      at System.Windows.Forms.Button.WndProc(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   };
   Exception.target.void_function = "WinPaletter.CreateInstance()";
   Exception.assembly = "WinPaletter, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null";
   Exception.assembly.file = "D:\\Downloads🔽\\WinPaletter\\WinPaletter.exe";
   Exception.HRESULT = -2146233079;
   Inner.exception.message = "Object reference not set to an instance of an object.";
   Exception.type = "System.NullReferenceException";
   Inner.exception.stack.trace =
   {
      at WinPaletter.Tabs.TitlebarExtender.updateBackDrop()
      at WinPaletter.Tabs.TitlebarExtender.OnSizeChanged(EventArgs e)
      at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
      at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
      at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
      at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
      at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
      at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
      at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
      at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
      at System.Windows.Forms.ContainerControl.ResumeAllLayout(Control start, Boolean performLayout)
      at System.Windows.Forms.ContainerControl.OnFontChanged(EventArgs e)
      at System.Windows.Forms.Form.OnFontChanged(EventArgs e)
      at System.Windows.Forms.Control.set_Font(Font value)
      at WinPaletter.MainForm.InitializeComponent()
      at WinPaletter.MainForm..ctor()
   };
   Inner.exception.target.void_function = "WinPaletter.updateBackDrop()";
   Inner.exception.assembly = "WinPaletter, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null";
   Inner.exception.assembly.file = "D:\\Downloads🔽\\WinPaletter\\WinPaletter.exe";
   Inner.exception.HRESULT = -2147467261;
```

## **Screenshots/Screen records**
- Don't add screenshot to exception error dialog if you already wrote WinPaletter Log.

## **Additional context**
There is enough information above

**Comment by Abdelrhman-AK** [comment]
And please tell me if you're disabling transparency effect on Windows or using another theme (visual styles) for Windows.

**Comment by Andrew-Sor** [comment]
Well I'm using the MacOS theme and I didn't turn off the transparency effect

**Comment by Andrew-Sor** [comment]
> You can safely ignore this error.

Unfortunately, after that it gives the error again, but if you ignore it this time, it will close

**Comment by Abdelrhman-AK** [comment]
When I work on the next version, I'll fix it for sure.

**Comment by Abdelrhman-AK** [comment]
Can you use both `WinPaletter-DEBUG.exe` with `WinPaletter.pdb` so that I can trace the issue. I can't reproduce it at all.
Download both from releases if you don't have them.

**Comment by Andrew-Sor** [comment]
> Can you use both `WinPaletter-DEBUG.exe` with `WinPaletter.pdb` so that I can trace the issue. I can't reproduce it at all.

I thought about that too... But they also gave an error...

> I reproduced and fixed it. Please wait for a new update, which will likely be the final one for me as I won't have time after a few days.

Excellent thank you! Will wait

**Comment by Andrew-Sor** [comment]
By the way, the old version works
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/133566800/7d9bad2d-02d8-4a8f-81d8-9c5fd8aabc4f)

**Comment by Abdelrhman-AK** [comment]
There is something wrong I have fixed, it is in the tabs UI.

**Comment by Abdelrhman-AK** [comment]
That is because you have Windows 11. If you enabled classic context menu or used classic context menu in a Win32 app (for example: Registry Editor), you will notice the effect.

**Comment by Andrew-Sor** [comment]
> That is because you have Windows 11. If you enabled classic context menu or used classic context menu in a Win32 app (for example: Registry Editor), you will notice the effect.
> 
> ![image](https://private-user-images.githubusercontent.com/59510211/320947211-87e47367-038d-46dd-8306-98ae9c8f5fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2ODQ1OTUsIm5iZiI6MTcxMjY4NDI5NSwicGF0aCI6Ii81OTUxMDIxMS8zMjA5NDcyMTEtODdlNDczNjctMDM4ZC00NmRkLTgzMDYtOThhZTljOGY1ZmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE3MzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZWUyNmM5YjU4OWNmODRiNDA4MjYyMDlkYzIyYzRjMjA4Njk4MDE5OTAzOWE3OTRmNDU1Mzg0NWUxZTUwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOZcLAdS9US6YORjcbnzC1omTJEWyjUCH2Dq8vZV2wM)

It's clear. Thanks, but I like the new design better

**Comment by Andrew-Sor** [comment]
>  That is because you have Windows 11. If you enabled classic context menu or used classic context menu in a Win32 app (for example: Registry Editor), you will notice the effect.

 It's clear. Thanks, but I like the new design better

**Comment by Abdelrhman-AK** [comment]
>I like the new design better

Absolutely! Feel free to personalize your Windows as you like.

**Comment by Andrew-Sor** [comment]
Thank you! Now everything works great!

**Comment by Abdelrhman-AK** [comment]
You're welcome!
