### ISSUE TITLE
Error creating form: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by fruzelee** [Abdelrhman-AK/WinPaletter#229]
```cs
//General information
//...........................................................
   Report.Date = "Tuesday, 9 April, 2024 4:06:54 PM";
   OS = "Windows 11, 10.0.22631.3374, 64-bit";
   WinPaletter.Version = "1.0.9.0, Build: Release";
   WinPaletter.Language = "English";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "Error creating form: Object reference not set to an instance of an object.";
   Exception.type = "System.InvalidOperationException";
   Exception.stack.trace =
   {
      at WinPaletter.Forms.CreateInstance[T](T instance)
      at WinPaletter.Forms.get_MainForm()
      at WinPaletter.User.OnUserSwitch(UserChangeEventArgs e)
      at WinPaletter.User.set_SID(String value)
      at WinPaletter.UserSwitch.Button1_Click(Object sender, EventArgs e)
      at System.Windows.Forms.Control.OnClick(EventArgs e)
      at System.Windows.Forms.Button.OnClick(EventArgs e)
      at WinPaletter.UI.WP.Button.OnClick(EventArgs e)
      at System.Windows.Forms.Button.PerformClick()
      at WinPaletter.UserSwitch.Radio_DoubleClick(Object sender, EventArgs e)
      at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
      at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   };
   Exception.target.void_function = "WinPaletter.CreateInstance()";
   Exception.assembly = "WinPaletter, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null";
   Exception.assembly.file = "F:\\soft\\portable\\WinPaletter.exe";
   Exception.HRESULT = -2146233079;
   Inner.exception.message = "Object reference not set to an instance of an object.";
   Exception.type = "System.NullReferenceException";
   Inner.exception.stack.trace =
   {
      at WinPaletter.Tabs.TitlebarExtender.updateBackDrop()
      at WinPaletter.Tabs.TitlebarExtender.OnSizeChanged(EventArgs e)
      at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
      at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
      at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
      at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
      at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
      at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
      at System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
      at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
      at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
      at System.Windows.Forms.ContainerControl.ResumeAllLayout(Control start, Boolean performLayout)
      at System.Windows.Forms.ContainerControl.OnFontChanged(EventArgs e)
      at System.Windows.Forms.Form.OnFontChanged(EventArgs e)
      at System.Windows.Forms.Control.set_Font(Font value)
      at WinPaletter.MainForm.InitializeComponent()
      at WinPaletter.MainForm..ctor()
   };
   Inner.exception.target.void_function = "WinPaletter.updateBackDrop()";
   Inner.exception.assembly = "WinPaletter, Version=1.0.9.0, Culture=neutral, PublicKeyToken=null";
   Inner.exception.assembly.file = "F:\\soft\\portable\\WinPaletter.exe";
   Inner.exception.HRESULT = -2147467261;
```

**Comment by Abdelrhman-AK** [comment]
It will be fixed in the next and final update. It is identical to #228.
