### ISSUE TITLE
[1.0.9.1] Cursors Studio crashes when change the size

### ISSUE THREAD

**Issue by MuscularPuky** [Abdelrhman-AK/WinPaletter#230]
## **Describe the error**
When I try to change cursor size in Cursors Studio, WinPaletter starts crashloop.

## **How to reproduce the error**
1. Enter Cursors Studio
2. Load from current applied theme, then cursors aspect is disabled automatically
3. Default option is "rendered by WinPaletter". change to "From file".
4. Adjust size, it crashes

## **WinPaletter Log**
```cs
//General information
//...........................................................
   Report.Date = "2024년 4월 12일 금요일 오후 6:18:36";
   OS = "Windows 11, 10.0.26090.1, 64-bit";
   WinPaletter.Version = "1.0.9.1, Build: Release";
   WinPaletter.Language = "한국어(대한민국)";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "Value cannot be null.
Parameter name: image";
   Exception.type = "System.ArgumentNullException";
   Exception.stack.trace =
   {
      at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y)
      at WinPaletter.Paths.Draw(CursorOptions CursorOptions)
      at WinPaletter.UI.Controllers.CursorControl.OnPaint(PaintEventArgs e)
      at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
      at System.Windows.Forms.Control.WmPaint(Message& m)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
      at System.Windows.Forms.ContainerControl.WndProc(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
      at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   };
   Exception.target.void_function = "System.Drawing.DrawImage()";
   Exception.assembly = "System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a";
   Exception.assembly.file = "C:\\WINDOWS\\Microsoft.Net\\assembly\\GAC_MSIL\\System.Drawing\\v4.0_4.0.0.0__b03f5f7f11d50a3a\\System.Drawing.dll";
   Exception.HRESULT = -2147467261;
```

## **Screenshots/Screen records**
- Don't add screenshot to exception error dialog if you already wrote WinPaletter Log.
- If possible, add screenshots/Screen records of the wrong behaviour to help explain your problem.

## **Additional context**
- Add any other context about the problem here.

**Comment by Abdelrhman-AK** [comment]
I'll fix it and push a quick update today or tomorrow.
