### ISSUE TITLE
12,12,12 expection error

### ISSUE THREAD

**Issue by imongus** [Abdelrhman-AK/WinPaletter#232]
## **12,12,12 is not valid value for int32*
- 12,12,12 is not a valid value from int32

## **How to reproduce the error**
- Version 1.0.9.2, Windows 11, 10.0.22631.3447, 64-Bit

## **WinPaletter Log**
- I would put it here but it doesnt let me copy and paste it gives another errror.

**Comment by imongus** [comment]
also other than that the application works tottaly fine

**Comment by Abdelrhman-AK** [comment]
What did you do exactly to make this error happen?

You can try using both `WinPaletter-Debug.exe` and `WinPaletter.pdb` to make WinPaletter show extended error details.

**Comment by krisjyr** [comment]
Here's a picture of the error code: 
![image](https://github.com/Abdelrhman-AK/WinPaletter/assets/113598502/3e1f3f65-915e-4303-932b-cb29cb5e78d8)

Code is not copyable via the buttons, nor can one save it on .txt file. It seems to happen to me once i open WinPaletter and go into the themes shop/store.

**Comment by Abdelrhman-AK** [comment]
I'll fix this error.

**Comment by Abdelrhman-AK** [comment]
- Please open this path `%localappdata%\Abdelrhman-AK\WinPaletter\Reports` and give me the most recent file. Logs are automatically saved.

- I tried to reproduce the issue, but nothing happened to me. I opened all themes in the store and all the themes I have locally (offline), but the problem didn't occur. I've made some code tweaks, but I'm not sure if they'll work for you.

- One last idea I have is that the comma `,` in `12, 12, 12` might be a different Unicode character, which could be why the color translator couldn't parse it. To investigate further, I've requested the log file.

**Comment by Abdelrhman-AK** [comment]
If possible, please record a screen capture of all the issues you are encountering starting from WinPaletter's launch, including the problem with parsing the color `12, 12, 12` and the problem of pressing copy log and save log, by using Windows Snipping Tool or another tool.

**Comment by star-blob** [comment]
```cs
//General information
//...........................................................
   Report.Date = "2024. április 22., hétfő 21:28:27";
   OS = "Windows 11, 10.0.22631.3447, 64-bit";
   WinPaletter.Version = "1.0.9.2, Build: Release";
   WinPaletter.Language = "English";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "12, 12, 12 is not a valid value for Int32.";
   Exception.type = "System.Exception";
   Exception.stack.trace =
   {
      at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
      at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
      at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
      at WinPaletter.WinTerminal.Types.ColorConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
      at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
      at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
      at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
      at Newtonsoft.Json.Linq.JToken.ToObject[T]()
      at WinPaletter.Theme.Manager.ExtendTerminalComptability(JObject& json)
      at WinPaletter.Theme.Manager..ctor(Source Source, String File, Boolean ignoreExtractionThemePack, Boolean ignoreErrors)
   };
   Exception.target.void_function = "System.ConvertFrom()";
   Exception.assembly = "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089";
   Exception.assembly.file = "C:\\WINDOWS\\Microsoft.Net\\assembly\\GAC_MSIL\\System\\v4.0_4.0.0.0__b77a5c561934e089\\System.dll";
   Exception.HRESULT = -2146233088;
   Inner.exception.message = "Input string was not in a correct format.";
   Exception.type = "System.FormatException";
   Inner.exception.stack.trace =
   {
      at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
      at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
      at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
      at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   };
   Inner.exception.target.void_function = "mscorlib.StringToNumber()";
   Inner.exception.assembly = "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089";
   Inner.exception.assembly.file = "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscorlib.dll";
   Inner.exception.HRESULT = -2146233033;
```

**Comment by Konomi12** [comment]
![Image](https://github.com/user-attachments/assets/c237991b-cb27-434c-85b7-16f8ed332b74)


the same situation when I try to enter the store

**Comment by Abdelrhman-AK** [comment]
I have made a fixed trial in version 1.0.9.4 that I'll post in a few weeks, but I am not sure if it will work properly or not as I cannot reproduce this issue. Please try again and tell me if that is fixed in the new update or not when it is released.

**Comment by Nek220** [comment]
same problem. So when is the update?

> I have made a fixed trial in version 1.0.9.4 that I'll post in a few weeks, but I am not sure if it will work properly or not as I cannot reproduce this issue. Please try again and tell me if that is fixed in the new update or not when it is released.

**Comment by Nek220** [comment]
> > same problem. So when is the update?
> 
> Next Saturday or Sunday.

so what? saturday and sunday are over) so i'm waiting for an update, more than my birthday

**Comment by Abdelrhman-AK** [comment]
I am uploading the new release and writing the changelog now. 
Please tell me if this bug is fixed or not when you try the new release.

And happy early birthday 🎂!

**Comment by Abdelrhman-AK** [comment]
Here you are: https://github.com/Abdelrhman-AK/WinPaletter/releases/tag/v1.0.9.4

**Comment by Nek220** [comment]
Fixed!!!
