### ISSUE TITLE
Cant open WinPaletter in win11. Exception Error

### ISSUE THREAD

**Issue by manwichman44** [Abdelrhman-AK/WinPaletter#234]
Every time I try to run the program, I get an Exception Error.

All I have to do is try to open the program.

- ```cs
//General information
//...........................................................
   Report.Date = "Saturday, May 18, 2024 8:26:13 PM";
   OS = "Windows 11, 10.0.22631.3593, 64-bit";
   WinPaletter.Version = "1.0.9.3, Build: Release";
   WinPaletter.Language = "English";
   WinPaletter.Debugging = false;

//Error details
//...........................................................
   Exception.message = "Object reference not set to an instance of an object.";
   Exception.type = "System.NullReferenceException";
   Exception.stack.trace =
   {
      at WinPaletter.Program.GetWallpaperFromRegistry()
      at WinPaletter.Program.FetchSuitableWallpaper(Manager TM, WindowStyle previewConfig)
      at WinPaletter.Program.InitializeApplication(Boolean showLoginDialog)
      at WinPaletter.User.OnUserSwitch(UserChangeEventArgs e)
      at WinPaletter.User.set_SID(String value)
      at WinPaletter.User.Login(Boolean ForceShow, Boolean SkipToCurrentUser)
      at WinPaletter.Program.InitializeApplication(Boolean showLoginDialog)
      at WinPaletter.Program.Main(String[] args)
   };
   Exception.target.void_function = "WinPaletter.GetWallpaperFromRegistry()";
   Exception.assembly = "WinPaletter, Version=1.0.9.3, Culture=neutral, PublicKeyToken=null";
   Exception.assembly.file = "C:\\Users\\Manwi\\Downloads\\WinPaletter.exe";
   Exception.HRESULT = -2147467261;
```

**Comment by Abdelrhman-AK** [comment]
Try changing your wallpaper into another image then reuse the previous image.
