### ISSUE TITLE
The application gives error message whenever I launch it.

### ISSUE THREAD

**Issue by Zliced13** [Abdelrhman-AK/WinPaletter#66]
### Log
```
• Date of report: Saturday, January 28, 2023 - 12:59:32 PM
• OS: Microsoft Windows 10 Pro - 10.0.19045.2486 - 64-bit
• WinPaletter Version: 1.0.6.9
--------

• Error Message:
   Conversion from string "" to type 'Integer' is not valid.

• Stack Trace:
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
   at WinPaletter.CP..ctor(Mode Mode, String PaletteFile, Boolean IgnoreWindowsTerminal)
   at WinPaletter.MainFrm.MainFrm_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Abdelrhman-AK** [comment]
- Is this your fisrt time using WinPaletter or did you update?
- If you updated it, send me a screenshot to your registry key 
`HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics`
- Try to downgrade to 1.0.6.3 and see if the same error happens or not.

**Comment by Zliced13** [comment]
> * Is this your fisrt time using WinPaletter or did you update?
> 
> * If you updated it, send me a screenshot to your registry key
>       `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics`
> 
> * Try to downgrade to 1.0.6.3 and see if the same error happens or not.

* No it's not my first time using this application
* ![(RegistryFinder)U4J0I3_01-28-2023](https://user-images.githubusercontent.com/101912712/215304608-d9aa6681-0f85-45f6-a57b-a98655a2b28c.jpg)
* The previous version works fine:
![(WinPaletter)s195z5_01-28-2023](https://user-images.githubusercontent.com/101912712/215304663-817ba207-8e4d-4391-b420-9f38db88ba15.jpg)

**Comment by Abdelrhman-AK** [comment]
![Screenshot_20230129-125902_Chrome.png](https://user-images.githubusercontent.com/59510211/215321728-e2b2cead-afe8-4903-9a6e-c80853b1405c.png)

I think that ShellIconSize is the reason of error. Try to set it to `32` and try again with WinPaletter 1.0.6.9

**Comment by Zliced13** [comment]
Sure I will try that.

**Comment by Zliced13** [comment]
@Abdelrhman-AK it works now, thank you for helping me.

**Comment by Abdelrhman-AK** [comment]
You're welcome!
