### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by SmirbYrneh420** [Abdelrhman-AK/WinPaletter#68]
![image](https://user-images.githubusercontent.com/110212580/217651529-fbdb3be0-b047-4617-8238-957fcac03424.png)
• Date of report: Wednesday, February 8, 2023 - 4:10:10 PM
• OS: Microsoft Windows 11 Home - 10.0.22623.1250 - 64-bit
• WinPaletter Version: 1.0.6.9
--------

• Error Message:
   Object reference not set to an instance of an object.

• Stack Trace:
   at WinPaletter.CP.ResetCursorsToAero()
   at WinPaletter.Uninstall.XenonButton6_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at WinPaletter.XenonButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Abdelrhman-AK** [comment]
I'll fix this
